export const FETCH_PRODUTOS = "FETCH_PRODUTOS";

export const FILTER_PRODUTOS_BY_SIZE = "FILTER_PRODUTOS_BY_SIZE";

export const ORDER_PRODUTOS_BY_PRICE = "ORDER_PRODUTOS_BY_PRICE";



export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_FROM_CART = " REMOVE_FROM_CART";

