export const FETCH_PRODUTOS = "FETCH_PRODUTOS";

export const FILTER_PRODUTOS_BY_SIZE = "FILTER_PRODUTOS_BY_SIZE";

export const ORDER_PRODUTOS_BY_PRICE = "ORDER_PRODUTOS_BY_PRICE";

export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_FROM_CART = " REMOVE_FROM_CART";



export const CREATE_ORDER = "CREATE_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CLEAR_CART = "CLEAR_CART";